### PR TITLE
Parse tag markup once per instance

### PR DESCRIPTION
**Pull request by ashmaroli**
This change ensures that if there is a single instance of `{% avatar foo %}` which may be *rendered multiple times*, the *tag_markup* or `text` parameter value isn't *parsed by Liquid* for each render.

### CODE REVIEW

**Comment by ashmaroli** [comment]
Thanks for the approval, Ben. But since the tests are failing, I'll have to think of an alternative..

**Comment by benbalter** [comment]
@ashmaroli Thanks for all the great PRs this week. Any interest in maintaining this plugin, either in your own namespace or in Jekyll's?

**Comment by ashmaroli** [comment]
> Any interest in maintaining this plugin, either in your own namespace or in Jekyll's?

@benbalter I've pinged @mattr- regarding his opinion on transferring this plugin into the Jekyll Org.
Will get back to you once I get a response from him.

**Comment by ashmaroli** [comment]
@benbalter Both Parker and Matt are of the opinion that it would be best if Jekyll Org adopts this project rather than have it transferred into my namespace. So, they may approach you for the transfer in the near future.

**Pull request merged**
